Style/Documentation:
    Enabled: false

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - bin/**/*
    - db/schema.rb
    - vendor/**/*

inherit_gem:
  rubocop-discourse: default.yml
